"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Globe } from "lucide-react"

export default function PrivacyPolicyPage() {
  const [language, setLanguage] = useState<"en" | "ar">("en")

  const privacyContent = {
    en: {
      title: "Privacy Policy",
      lastUpdated: "Last Updated: July 12, 2025",
      intro:
        "This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.",
      interpretation: {
        heading: "Interpretation and Definitions",
        subheading1: "Interpretation",
        text1:
          "The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.",
        subheading2: "Definitions",
        list: [
          {
            term: "Account",
            definition: "means a unique account created for You to access our Service or parts of our Service.",
          },
          {
            term: "Affiliate",
            definition:
              'means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.',
          },
          {
            term: "Application",
            definition:
              "means the software program provided by the Company downloaded by You on any electronic device, named MovieApp.",
          },
          {
            term: "Company",
            definition:
              '(referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to MovieApp.',
          },
          { term: "Country", definition: "refers to: United States." },
          {
            term: "Device",
            definition:
              "means any device that can access the Service such as a computer, a cellphone or a digital tablet.",
          },
          {
            term: "Personal Data",
            definition: "is any information that relates to an identified or identifiable individual.",
          },
          { term: "Service", definition: "refers to the Application or the Website or both." },
          {
            term: "Service Provider",
            definition:
              "means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.",
          },
          {
            term: "Usage Data",
            definition:
              "refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
          },
          {
            term: "You",
            definition:
              "means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.",
          },
        ],
      },
      collectingData: {
        heading: "Collecting and Using Your Personal Data",
        subheading1: "Types of Data Collected",
        subheading2: "Personal Data",
        text1:
          "While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:",
        list1: [
          "Email address",
          "First name and last name",
          "Phone number",
          "Address, State, Province, ZIP/Postal code, City",
          "Usage Data",
        ],
        subheading3: "Usage Data",
        text2: "Usage Data is collected automatically when using the Service.",
        text3:
          "Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.",
        text4:
          "When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.",
        text5:
          "We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.",
      },
      useOfData: {
        heading: "Use of Your Personal Data",
        text1: "The Company may use Personal Data for the following purposes:",
        list: [
          "To provide and maintain our Service, including to monitor the usage of our Service.",
          "To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.",
          "For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.",
          "To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.",
          "To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.",
          "To manage Your requests: To attend and manage Your requests to Us.",
          "For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.",
          "For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.",
        ],
      },
      disclosureOfData: {
        heading: "Disclosure of Your Personal Data",
        subheading1: "With Service Providers",
        text1:
          "We may share Your personal information with Service Providers to monitor and analyze the use of our Service, to contact You.",
        subheading2: "For Business Transfers",
        text2:
          "We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.",
        subheading3: "With Affiliates",
        text3:
          "We may share Your information with Our Affiliates, in which case we will require those affiliates to honor this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.",
        subheading4: "With Business Partners",
        text4:
          "We may share Your information with Our business partners to offer You certain products, services or promotions.",
        subheading5: "With other users",
        text5:
          "When You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.",
        subheading6: "With Your consent",
        text6: "We may disclose Your personal information for any other purpose with Your consent.",
      },
      retentionOfData: {
        heading: "Retention of Your Personal Data",
        text1:
          "The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.",
        text2:
          "The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer time periods.",
      },
      transferOfData: {
        heading: "Transfer of Your Personal Data",
        text1:
          "Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.",
        text2:
          "Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.",
        text3:
          "The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.",
      },
      deleteYourData: {
        heading: "Delete Your Personal Data",
        text1:
          "You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.",
        text2: "Our Service may give You the ability to delete certain information about You from within the Service.",
        text3:
          "You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.",
        text4:
          "Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.",
      },
      disclosureForLawEnforcement: {
        heading: "Disclosure for Law Enforcement",
        text1:
          "Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).",
      },
      otherLegalRequirements: {
        heading: "Other Legal Requirements",
        text1: "The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:",
        list: [
          "Comply with a legal obligation",
          "Protect and defend the rights or property of the Company",
          "Prevent or investigate possible wrongdoing in connection with the Service",
          "Protect the personal safety of Users of the Service or the public",
          "Protect against legal liability",
        ],
      },
      securityOfData: {
        heading: "Security of Your Personal Data",
        text1:
          "The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.",
      },
      childrensPrivacy: {
        heading: "Children's Privacy",
        text1:
          "Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.",
        text2:
          "If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.",
      },
      linksToOtherWebsites: {
        heading: "Links to Other Websites",
        text1:
          "Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.",
        text2:
          "We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.",
      },
      changesToPolicy: {
        heading: "Changes to this Privacy Policy",
        text1:
          "We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.",
        text2:
          'We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.',
        text3:
          "You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.",
      },
      contactUs: {
        heading: "Contact Us",
        text1: "If you have any questions about this Privacy Policy, You can contact us:",
        list: ["By email: support@movieapp.com", "By visiting this page on our website: www.movieapp.com/contact"],
      },
    },
    ar: {
      title: "سياسة الخصوصية",
      lastUpdated: "آخر تحديث: 12 يوليو 2025",
      intro:
        "تصف سياسة الخصوصية هذه سياساتنا وإجراءاتنا بشأن جمع معلوماتك واستخدامها والكشف عنها عند استخدامك للخدمة وتخبرك بحقوق الخصوصية الخاصة بك وكيف يحميك القانون.",
      interpretation: {
        heading: "التفسير والتعريفات",
        subheading1: "التفسير",
        text1:
          "الكلمات التي تبدأ بحرف كبير لها معانٍ محددة بموجب الشروط التالية. يكون للتعريفات التالية نفس المعنى بغض النظر عما إذا كانت تظهر بصيغة المفرد أو الجمع.",
        subheading2: "التعريفات",
        list: [
          { term: "الحساب", definition: "يعني حسابًا فريدًا تم إنشاؤه لك للوصول إلى خدمتنا أو أجزاء من خدمتنا." },
          {
            term: "الشركة التابعة",
            definition:
              'تعني كيانًا يتحكم في طرف أو يخضع لسيطرة مشتركة معه، حيث تعني "السيطرة" ملكية 50% أو أكثر من الأسهم أو حصص الملكية أو الأوراق المالية الأخرى التي يحق لها التصويت لانتخاب المديرين أو أي سلطة إدارية أخرى.',
          },
          {
            term: "التطبيق",
            definition:
              "يعني برنامج الكمبيوتر الذي توفره الشركة والذي قمت بتنزيله على أي جهاز إلكتروني، ويسمى MovieApp.",
          },
          {
            term: "الشركة",
            definition: '(يشار إليها في هذه الاتفاقية بـ "الشركة" أو "نحن" أو "لنا" أو "خاصتنا") تشير إلى MovieApp.',
          },
          { term: "البلد", definition: "يشير إلى: الولايات المتحدة." },
          {
            term: "الجهاز",
            definition: "يعني أي جهاز يمكنه الوصول إلى الخدمة مثل الكمبيوتر أو الهاتف المحمول أو الجهاز اللوحي الرقمي.",
          },
          { term: "البيانات الشخصية", definition: "هي أي معلومات تتعلق بفرد محدد أو يمكن التعرف عليه." },
          { term: "الخدمة", definition: "تشير إلى التطبيق أو الموقع الإلكتروني أو كليهما." },
          {
            term: "مقدم الخدمة",
            definition:
              "يعني أي شخص طبيعي أو اعتباري يقوم بمعالجة البيانات نيابة عن الشركة. يشير إلى شركات أو أفراد من طرف ثالث توظفهم الشركة لتسهيل الخدمة، أو لتقديم الخدمة نيابة عن الشركة، أو لأداء خدمات تتعلق بالخدمة أو لمساعدة الشركة في تحليل كيفية استخدام الخدمة.",
          },
          {
            term: "بيانات الاستخدام",
            definition:
              "تشير إلى البيانات التي يتم جمعها تلقائيًا، سواء تم إنشاؤها عن طريق استخدام الخدمة أو من البنية التحتية للخدمة نفسها (على سبيل المثال، مدة زيارة الصفحة).",
          },
          {
            term: "أنت",
            definition:
              "تعني الفرد الذي يصل إلى الخدمة أو يستخدمها، أو الشركة، أو أي كيان قانوني آخر نيابة عن هذا الفرد الذي يصل إلى الخدمة أو يستخدمها، حسب الاقتضاء.",
          },
        ],
      },
      collectingData: {
        heading: "جمع واستخدام بياناتك الشخصية",
        subheading1: "أنواع البيانات التي يتم جمعها",
        subheading2: "البيانات الشخصية",
        text1:
          "أثناء استخدامك لخدمتنا، قد نطلب منك تزويدنا بمعلومات تعريف شخصية معينة يمكن استخدامها للاتصال بك أو التعرف عليك. قد تتضمن معلومات التعريف الشخصية، على سبيل المثال لا الحصر:",
        list1: [
          "عنوان البريد الإلكتروني",
          "الاسم الأول واسم العائلة",
          "رقم الهاتف",
          "العنوان، الولاية، المقاطعة، الرمز البريدي، المدينة",
          "بيانات الاستخدام",
        ],
        subheading3: "بيانات الاستخدام",
        text2: "يتم جمع بيانات الاستخدام تلقائيًا عند استخدام الخدمة.",
        text3:
          "قد تتضمن بيانات الاستخدام معلومات مثل عنوان بروتوكول الإنترنت لجهازك (مثل عنوان IP)، ونوع المتصفح، وإصدار المتصفح، والصفحات التي تزورها من خدمتنا، ووقت وتاريخ زيارتك، والوقت الذي تقضيه في تلك الصفحات، ومعرفات الجهاز الفريدة، وغيرها من بيانات التشخيص.",
        text4:
          "عندما تصل إلى الخدمة عن طريق جهاز محمول أو من خلاله، قد نجمع بعض المعلومات تلقائيًا، بما في ذلك، على سبيل المثال لا الحصر، نوع الجهاز المحمول الذي تستخدمه، ومعرف جهازك المحمول الفريد، وعنوان IP لجهازك المحمول، ونظام تشغيل جهازك المحمول، ونوع متصفح الإنترنت المحمول الذي تستخدمه، ومعرفات الجهاز الفريدة، وغيرها من بيانات التشخيص.",
        text5:
          "قد نجمع أيضًا المعلومات التي يرسلها متصفحك كلما زرت خدمتنا أو عندما تصل إلى الخدمة عن طريق جهاز محمول أو من خلاله.",
      },
      useOfData: {
        heading: "استخدام بياناتك الشخصية",
        text1: "قد تستخدم الشركة البيانات الشخصية للأغراض التالية:",
        list: [
          "لتقديم خدمتنا وصيانتها، بما في ذلك مراقبة استخدام خدمتنا.",
          "لإدارة حسابك: لإدارة تسجيلك كمستخدم للخدمة. يمكن أن تمنحك البيانات الشخصية التي تقدمها إمكانية الوصول إلى وظائف مختلفة للخدمة المتاحة لك كمستخدم مسجل.",
          "لأداء عقد: تطوير، والامتثال، وتنفيذ عقد الشراء للمنتجات أو العناصر أو الخدمات التي اشتريتها أو أي عقد آخر معنا من خلال الخدمة.",
          "للاتصال بك: للاتصال بك عبر البريد الإلكتروني أو المكالمات الهاتفية أو الرسائل القصيرة أو غيرها من أشكال الاتصال الإلكتروني المكافئة، مثل إشعارات الدفع لتطبيق الهاتف المحمول فيما يتعلق بالتحديثات أو الاتصالات الإعلامية المتعلقة بالوظائف أو المنتجات أو الخدمات المتعاقد عليها، بما في ذلك تحديثات الأمان، عند الضرورة أو المعقول لتنفيذها.",
          "لتزويدك بالأخبار والعروض الخاصة والمعلومات العامة حول السلع والخدمات والأحداث الأخرى التي نقدمها والتي تشبه تلك التي اشتريتها أو استفسرت عنها بالفعل ما لم تكن قد اخترت عدم تلقي هذه المعلومات.",
          "لإدارة طلباتك: لحضور وإدارة طلباتك إلينا.",
          "لعمليات نقل الأعمال: قد نستخدم معلوماتك لتقييم أو إجراء دمج أو تصفية أو إعادة هيكلة أو إعادة تنظيم أو حل أو أي بيع أو نقل آخر لبعض أو كل أصولنا، سواء كمنشأة مستمرة أو كجزء من إفلاس أو تصفية أو إجراء مماثل، حيث تكون البيانات الشخصية التي نحتفظ بها عن مستخدمي خدمتنا من بين الأصول المنقولة.",
          "لأغراض أخرى: قد نستخدم معلوماتك لأغراض أخرى، مثل تحليل البيانات، وتحديد اتجاهات الاستخدام، وتحديد فعالية حملاتنا الترويجية، وتقييم وتحسين خدمتنا ومنتجاتنا وخدماتنا وتسويقنا وتجربتك.",
        ],
      },
      disclosureOfData: {
        heading: "الكشف عن بياناتك الشخصية",
        subheading1: "مع مقدمي الخدمات",
        text1: "قد نشارك معلوماتك الشخصية مع مقدمي الخدمات لمراقبة وتحليل استخدام خدمتنا، وللاتصال بك.",
        subheading2: "لعمليات نقل الأعمال",
        text2:
          "قد نشارك أو ننقل معلوماتك الشخصية فيما يتعلق بأي دمج أو بيع لأصول الشركة أو تمويل أو استحواذ على كل أو جزء من أعمالنا لشركة أخرى، أو أثناء المفاوضات بشأن ذلك.",
        subheading3: "مع الشركات التابعة",
        text3:
          "قد نشارك معلوماتك مع الشركات التابعة لنا، وفي هذه الحالة سنطلب من تلك الشركات التابعة الالتزام بسياسة الخصوصية هذه. تشمل الشركات التابعة شركتنا الأم وأي شركات فرعية أخرى أو شركاء في مشاريع مشتركة أو شركات أخرى نتحكم فيها أو تخضع لسيطرة مشتركة معنا.",
        subheading4: "مع شركاء الأعمال",
        text4: "قد نشارك معلوماتك مع شركاء أعمالنا لتقديم منتجات أو خدمات أو عروض ترويجية معينة لك.",
        subheading5: "مع مستخدمين آخرين",
        text5:
          "عندما تشارك معلومات شخصية أو تتفاعل بطريقة أخرى في المناطق العامة مع مستخدمين آخرين، قد يتم عرض هذه المعلومات من قبل جميع المستخدمين وقد يتم توزيعها علنًا خارج الخدمة.",
        subheading6: "بموافقتك",
        text6: "قد نكشف عن معلوماتك الشخصية لأي غرض آخر بموافقتك.",
      },
      retentionOfData: {
        heading: "الاحتفاظ ببياناتك الشخصية",
        text1:
          "ستحتفظ الشركة ببياناتك الشخصية فقط طالما كان ذلك ضروريًا للأغراض المنصوص عليها في سياسة الخصوصية هذه. سنحتفظ ببياناتك الشخصية ونستخدمها بالقدر اللازم للامتثال لالتزاماتنا القانونية (على سبيل المثال، إذا كنا مطالبين بالاحتفاظ ببياناتك للامتثال للقوانين المعمول بها)، وحل النزاعات، وإنفاذ اتفاقياتنا وسياساتنا القانونية.",
        text2:
          "ستحتفظ الشركة أيضًا ببيانات الاستخدام لأغراض التحليل الداخلي. يتم الاحتفاظ ببيانات الاستخدام بشكل عام لفترة زمنية أقصر، باستثناء عندما يتم استخدام هذه البيانات لتعزيز الأمان أو لتحسين وظائف خدمتنا، أو عندما نكون ملزمين قانونًا بالاحتفاظ بهذه البيانات لفترات زمنية أطول.",
      },
      transferOfData: {
        heading: "نقل بياناتك الشخصية",
        text1:
          "تتم معالجة معلوماتك، بما في ذلك البيانات الشخصية، في مكاتب تشغيل الشركة وفي أي أماكن أخرى يتواجد فيها الأطراف المشاركون في المعالجة. وهذا يعني أنه قد يتم نقل هذه المعلومات إلى – والاحتفاظ بها على – أجهزة كمبيوتر تقع خارج ولايتك أو مقاطعتك أو بلدك أو أي ولاية قضائية حكومية أخرى حيث قد تختلف قوانين حماية البيانات عن تلك الموجودة في ولايتك القضائية.",
        text2: "موافقتك على سياسة الخصوصية هذه متبوعة بتقديمك لهذه المعلومات يمثل موافقتك على هذا النقل.",
        text3:
          "ستتخذ الشركة جميع الخطوات الضرورية بشكل معقول لضمان معالجة بياناتك بشكل آمن ووفقًا لسياسة الخصوصية هذه، ولن يتم نقل بياناتك الشخصية إلى منظمة أو بلد ما لم تكن هناك ضوابط كافية مطبقة بما في ذلك أمان بياناتك والمعلومات الشخصية الأخرى.",
      },
      deleteYourData: {
        heading: "حذف بياناتك الشخصية",
        text1: "لديك الحق في حذف أو طلب مساعدتنا في حذف البيانات الشخصية التي جمعناها عنك.",
        text2: "قد تمنحك خدمتنا القدرة على حذف معلومات معينة عنك من داخل الخدمة.",
        text3:
          "يمكنك تحديث معلوماتك أو تعديلها أو حذفها في أي وقت عن طريق تسجيل الدخول إلى حسابك، إذا كان لديك حساب، وزيارة قسم إعدادات الحساب الذي يسمح لك بإدارة معلوماتك الشخصية. يمكنك أيضًا الاتصال بنا لطلب الوصول إلى أي معلومات شخصية قدمتها لنا أو تصحيحها أو حذفها.",
        text4:
          "يرجى ملاحظة، مع ذلك، أننا قد نحتاج إلى الاحتفاظ بمعلومات معينة عندما يكون لدينا التزام قانوني أو أساس قانوني للقيام بذلك.",
      },
      disclosureForLawEnforcement: {
        heading: "الكشف لإنفاذ القانون",
        text1:
          "في ظل ظروف معينة، قد يُطلب من الشركة الكشف عن بياناتك الشخصية إذا كان ذلك مطلوبًا بموجب القانون أو استجابة لطلبات صالحة من السلطات العامة (مثل محكمة أو وكالة حكومية).",
      },
      otherLegalRequirements: {
        heading: "متطلبات قانونية أخرى",
        text1: "قد تكشف الشركة عن بياناتك الشخصية بحسن نية إذا كان هذا الإجراء ضروريًا من أجل:",
        list: [
          "الامتثال لالتزام قانوني",
          "حماية حقوق أو ممتلكات الشركة والدفاع عنها",
          "منع أو التحقيق في أي مخالفات محتملة تتعلق بالخدمة",
          "حماية السلامة الشخصية لمستخدمي الخدمة أو الجمهور",
          "الحماية من المسؤولية القانونية",
        ],
      },
      securityOfData: {
        heading: "أمان بياناتك الشخصية",
        text1:
          "أمان بياناتك الشخصية مهم بالنسبة لنا، ولكن تذكر أن أي طريقة نقل عبر الإنترنت، أو طريقة تخزين إلكترونية ليست آمنة بنسبة 100%. بينما نسعى جاهدين لاستخدام وسائل مقبولة تجاريًا لحماية بياناتك الشخصية، لا يمكننا ضمان أمانها المطلق.",
      },
      childrensPrivacy: {
        heading: "خصوصية الأطفال",
        text1:
          "خدمتنا لا تستهدف أي شخص دون سن 13 عامًا. نحن لا نجمع عن علم معلومات تعريف شخصية من أي شخص دون سن 13 عامًا. إذا كنت والدًا أو وصيًا وكنت على علم بأن طفلك قد زودنا ببيانات شخصية، فيرجى الاتصال بنا. إذا علمنا أننا جمعنا بيانات شخصية من أي شخص دون سن 13 عامًا دون التحقق من موافقة الوالدين، فإننا نتخذ خطوات لإزالة تلك المعلومات من خوادمنا.",
        text2:
          "إذا احتجنا إلى الاعتماد على الموافقة كأساس قانوني لمعالجة معلوماتك ويتطلب بلدك موافقة من أحد الوالدين، فقد نطلب موافقة والديك قبل جمع واستخدام تلك المعلومات.",
      },
      linksToOtherWebsites: {
        heading: "روابط لمواقع أخرى",
        text1:
          "قد تحتوي خدمتنا على روابط لمواقع ويب أخرى لا نقوم بتشغيلها. إذا نقرت على رابط طرف ثالث، فسيتم توجيهك إلى موقع هذا الطرف الثالث. ننصحك بشدة بمراجعة سياسة الخصوصية لكل موقع تزوره.",
        text2:
          "ليس لدينا أي سيطرة على محتوى أو سياسات الخصوصية أو ممارسات أي مواقع أو خدمات طرف ثالث ولا نتحمل أي مسؤولية عنها.",
      },
      changesToPolicy: {
        heading: "تغييرات على سياسة الخصوصية هذه",
        text1:
          "قد نقوم بتحديث سياسة الخصوصية الخاصة بنا من وقت لآخر. سنخطرك بأي تغييرات عن طريق نشر سياسة الخصوصية الجديدة على هذه الصفحة.",
        text2:
          'سنخبرك عبر البريد الإلكتروني و/أو إشعار بارز على خدمتنا، قبل أن يصبح التغيير ساري المفعول ونقوم بتحديث تاريخ "آخر تحديث" في الجزء العلوي من سياسة الخصوصية هذه.',
        text3:
          "يُنصح بمراجعة سياسة الخصوصية هذه بشكل دوري لأي تغييرات. تصبح التغييرات على سياسة الخصوصية هذه سارية المفعول عند نشرها على هذه الصفحة.",
      },
      contactUs: {
        heading: "اتصل بنا",
        text1: "إذا كان لديك أي أسئلة حول سياسة الخصوصية هذه، يمكنك الاتصال بنا:",
        list: [
          "عبر البريد الإلكتروني: support@movieapp.com",
          "عن طريق زيارة هذه الصفحة على موقعنا: www.movieapp.com/contact",
        ],
      },
    },
  }

  const content = privacyContent[language]

  return (
    <div className="min-h-screen bg-background-dark text-text-white pb-16 md:pb-0">
      <div className="container mx-auto px-4 py-6">
        <h1 className="text-3xl font-bold mb-4 text-center">{content.title}</h1>
        <p className="text-sm text-gray-400 text-center mb-6">{content.lastUpdated}</p>

        <div className="flex justify-end mb-4">
          <Button
            variant="outline"
            size="sm"
            className="border-border-gray text-gray-400 hover:bg-background-light bg-transparent"
            onClick={() => setLanguage(language === "en" ? "ar" : "en")}
          >
            <Globe className="h-4 w-4 mr-2" />
            {language === "en" ? "العربية" : "English"}
          </Button>
        </div>

        <div className="prose prose-invert max-w-none text-text-white">
          <p>{content.intro}</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">{content.interpretation.heading}</h2>
          <h3 className="text-xl font-semibold mt-6 mb-3">{content.interpretation.subheading1}</h3>
          <p>{content.interpretation.text1}</p>
          <h3 className="text-xl font-semibold mt-6 mb-3">{content.interpretation.subheading2}</h3>
          <ul className="list-disc pl-5 space-y-2">
            {content.interpretation.list.map((item, index) => (
              <li key={index}>
                <strong>{item.term}:</strong> {item.definition}
              </li>
            ))}
          </ul>

          <h2 className="text-2xl font-bold mt-8 mb-4">{content.collectingData.heading}</h2>
          <h3 className="text-xl font-semibold mt-6 mb-3">{content.collectingData.subheading1}</h3>
          <h4 className="text-lg font-semibold mt-4 mb-2">{content.collectingData.subheading2}</h4>
          <p>{content.collectingData.text1}</p>
          <ul className="list-disc pl-5 space-y-1">
            {content.collectingData.list1.map((item, index) => (
              <li key={index}>{item}</li>
            ))}
          </ul>
          <h4 className="text-lg font-semibold mt-4 mb-2">{content.collectingData.subheading3}</h4>
          <p>{content.collectingData.text2}</p>
          <p>{content.collectingData.text3}</p>
          <p>{content.collectingData.text4}</p>
          <p>{content.collectingData.text5}</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">{content.useOfData.heading}</h2>
          <p>{content.useOfData.text1}</p>
          <ul className="list-disc pl-5 space-y-2">
            {content.useOfData.list.map((item, index) => (
              <li key={index}>{item}</li>
            ))}
          </ul>

          <h2 className="text-2xl font-bold mt-8 mb-4">{content.disclosureOfData.heading}</h2>
          <h3 className="text-xl font-semibold mt-6 mb-3">{content.disclosureOfData.subheading1}</h3>
          <p>{content.disclosureOfData.text1}</p>
          <h3 className="text-xl font-semibold mt-6 mb-3">{content.disclosureOfData.subheading2}</h3>
          <p>{content.disclosureOfData.text2}</p>
          <h3 className="text-xl font-semibold mt-6 mb-3">{content.disclosureOfData.subheading3}</h3>
          <p>{content.disclosureOfData.text3}</p>
          <h3 className="text-xl font-semibold mt-6 mb-3">{content.disclosureOfData.subheading4}</h3>
          <p>{content.disclosureOfData.text4}</p>
          <h3 className="text-xl font-semibold mt-6 mb-3">{content.disclosureOfData.subheading5}</h3>
          <p>{content.disclosureOfData.text5}</p>
          <h3 className="text-xl font-semibold mt-6 mb-3">{content.disclosureOfData.subheading6}</h3>
          <p>{content.disclosureOfData.text6}</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">{content.retentionOfData.heading}</h2>
          <p>{content.retentionOfData.text1}</p>
          <p>{content.retentionOfData.text2}</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">{content.transferOfData.heading}</h2>
          <p>{content.transferOfData.text1}</p>
          <p>{content.transferOfData.text2}</p>
          <p>{content.transferOfData.text3}</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">{content.deleteYourData.heading}</h2>
          <p>{content.deleteYourData.text1}</p>
          <p>{content.deleteYourData.text2}</p>
          <p>{content.deleteYourData.text3}</p>
          <p>{content.deleteYourData.text4}</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">{content.disclosureForLawEnforcement.heading}</h2>
          <p>{content.disclosureForLawEnforcement.text1}</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">{content.otherLegalRequirements.heading}</h2>
          <p>{content.otherLegalRequirements.text1}</p>
          <ul className="list-disc pl-5 space-y-2">
            {content.otherLegalRequirements.list.map((item, index) => (
              <li key={index}>{item}</li>
            ))}
          </ul>

          <h2 className="text-2xl font-bold mt-8 mb-4">{content.securityOfData.heading}</h2>
          <p>{content.securityOfData.text1}</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">{content.childrensPrivacy.heading}</h2>
          <p>{content.childrensPrivacy.text1}</p>
          <p>{content.childrensPrivacy.text2}</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">{content.linksToOtherWebsites.heading}</h2>
          <p>{content.linksToOtherWebsites.text1}</p>
          <p>{content.linksToOtherWebsites.text2}</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">{content.changesToPolicy.heading}</h2>
          <p>{content.changesToPolicy.text1}</p>
          <p>{content.changesToPolicy.text2}</p>
          <p>{content.changesToPolicy.text3}</p>

          <h2 className="text-2xl font-bold mt-8 mb-4">{content.contactUs.heading}</h2>
          <p>{content.contactUs.text1}</p>
          <ul className="list-disc pl-5 space-y-1">
            {content.contactUs.list.map((item, index) => (
              <li key={index}>{item}</li>
            ))}
          </ul>
        </div>
      </div>
    </div>
  )
}
